# This file was generated by GoReleaser. DO NOT EDIT.
cask "pvetui" do
  # rubocop:disable Cask/StanzaOrder, Cask/StanzaGrouping

  name "pvetui"
  desc "Terminal user interface (TUI) for Proxmox VE"
  homepage "https://github.com/devnullvoid/pvetui"
  version "1.0.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pvetui"

  on_macos do
    on_intel do
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_darwin_amd64.tar.gz"
      sha256 "99b9e95d89b97d4df14627d73effe49b6c2aab8c78602fb14315b64bdbb73f61"
    end
    on_arm do
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_darwin_arm64.tar.gz"
      sha256 "aec6542310490fcba57667370175a9eaee664c4da37e4d3b2d447f99ec5b5fde"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_linux_amd64.tar.gz"
      sha256 "17ecf42a7d096bf36598bfccb2a9535351dca48529c263100a0a244f314a05b8"
    end
    on_arm do
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_linux_arm64.tar.gz"
      sha256 "2a25b44aac77ff8136d24beb85d95efeb97397f0fc3241f820c3f4d7bf70c5f8"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pvetui"] if OS.mac?
  end

  caveats do
    "pvetui requires a Proxmox VE server to connect to."
    "Run `pvetui --help` to see configuration options."
  end

  # No zap stanza required
end
