# This file was generated by GoReleaser. DO NOT EDIT.
cask "pvetui" do
  # rubocop:disable Cask/StanzaOrder, Cask/StanzaGrouping

  version "1.4.1"

  on_macos do
    on_intel do
      sha256 "d270bc3daa4a13d52d66859e1f65a0223ff185dc110eddc14e89d9a1f667cb84"
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e88408bad8e41be8f0758d0831c748a27e8d84308aeac0f51e70cbb2c548c80"
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7f810c0ca0e4d316b93b15c87dee0d861471bd0f163551c2e66980996764464c"
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bcc823b63dbceeba6c22fd3af459799d11a436777d44f7a54c870ac7dc6ef633"
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pvetui"
  desc "Terminal user interface (TUI) for Proxmox VE"
  homepage "https://github.com/devnullvoid/pvetui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pvetui"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pvetui"] if OS.mac?
  end

  # No zap stanza required

  caveats <<~EOS
    pvetui requires a Proxmox VE server to connect to.
    Run `pvetui --help` to see configuration options.
  EOS
end
