# This file was generated by GoReleaser. DO NOT EDIT.
cask "pvetui" do
  # rubocop:disable Cask/StanzaOrder, Cask/StanzaGrouping

  name "pvetui"
  desc "Terminal user interface (TUI) for Proxmox VE"
  homepage "https://github.com/devnullvoid/pvetui"
  version "1.0.20"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pvetui"

  on_macos do
    on_intel do
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_darwin_amd64.tar.gz"
      sha256 "fb484e5ea42e9b28e39184906c499c9c2be549c2264cb1c3bfd7fae75305ec23"
    end
    on_arm do
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_darwin_arm64.tar.gz"
      sha256 "cb9def839b1631164cef259579f97ebdffa6a21d8fe730a68207fefaa644fdea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_linux_amd64.tar.gz"
      sha256 "1807895ab00c2d2638f6d01016612eb10ce40a64bdb46e7d0dd1c4e26e17ca8c"
    end
    on_arm do
      url "https://github.com/devnullvoid/pvetui/releases/download/v#{version}/pvetui_#{version}_linux_arm64.tar.gz"
      sha256 "55c7c3f34c4af459dc7c71c043d49b94495913e021943ca1e4ea607f7c676cd6"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pvetui"] if OS.mac?
  end

  caveats do
    "pvetui requires a Proxmox VE server to connect to."
    "Run `pvetui --help` to see configuration options."
  end

  # No zap stanza required
end
